apps/rooms/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'rooms', views.RoomViewSet, basename='api-rooms')
router.register(r'messages', views.MessageViewSet, basename='api-messages')

urlpatterns = [
    path('', views.RoomsListView.as_view(), name='list'),
    path('create/', views.RoomCreateView.as_view(), name='create'),
    path('rooms/<int:pk>/', views.RoomDetailView.as_view(), name='detail'),
    path('api/', include(router.urls)),
]

room_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.rooms.urls', 'rooms'), namespace='rooms')),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path(
        'api-auth/',
        include(
            'rest_framework.urls',
            namespace='rest_framework',
        ),
    ),
]

apps/rooms/models.py
from django.db import models

# Create your models here.


class Room(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    room = models.ForeignKey(
        Room,
        on_delete=models.CASCADE,
        related_name='messages',
    )
    sender = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        related_name='messages',
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f'{self.sender}: {self.content}'

apps/rooms/forms.py
from django import forms
from .models import Room


class RoomForm(forms.ModelForm):
    """Form definition for Room."""

    class Meta:
        """Meta definition for Roomform."""

        model = Room
        fields = ('name',)
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'})}

apps/rooms/views.py
from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from rest_framework.viewsets import ReadOnlyModelViewSet
from rest_framework import permissions
from .models import Room, Message
from .forms import RoomForm
from .serializers import RoomSerializer, MessageSerializer, BaseRoomSerializer
import logging

logger = logging.getLogger('main')
# Create your views here.


class RoomCreateView(LoginRequiredMixin, CreateView):
    model = Room
    template_name = "rooms/create.html"
    form_class = RoomForm
    success_url = reverse_lazy('rooms:list')
    success_message = "New room '%(name)s'. Be the first one to start speaking"


class RoomsListView(ListView):
    model = Room
    template_name = "rooms/list.html"
    context_object_name = 'rooms'

    def get_queryset(self):
        queryset = super(RoomsListView, self).get_queryset()
        queryset = queryset.filter(
            name__icontains=self.request.GET.get('q', '')
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context


class RoomDetailView(LoginRequiredMixin, DetailView):
    model = Room
    template_name = "rooms/detail.html"
    context_object_name = 'room'
    queryset = Room.objects.all()


# API VIEWSETS
class RoomViewSet(ReadOnlyModelViewSet):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    permission_classes = [
        permissions.IsAuthenticatedOrReadOnly,
    ]

    def get_serializer_class(self):
        """This helps to keep consistency between views
        (that allow users to see rooms but not in detail)
        with the apis
        """
        if self.request.user.is_authenticated:
            return RoomSerializer
        return BaseRoomSerializer


class MessageViewSet(ReadOnlyModelViewSet):
    serializer_class = MessageSerializer
    permission_classes = [
        permissions.IsAuthenticated,
    ]

    def get_queryset(self):
        return Message.objects.filter(sender=self.request.user)

templates/rooms/create.html
{% extends 'base.html' %}


{% block head_content %}
<title>Create Room</title>
{% endblock head_content %}


{% block container %}
<form action="{% url 'rooms:create' %}" method="post">{% csrf_token %}
    {{ form.as_p}}
    <button class="btn btn-primary w-100" type="submit">Create Room</button>
</form>
{% endblock container %}

templates/rooms/detail.html
{% extends 'base.html' %}


{% block head_content %}
<title>{{room.name}}</title>
{% endblock head_content %}


{% block container %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

<div class="card">
    <div class="card-header text-center">
        <h3 class="card-title">{{room.name}}</h3>
    </div>
    <div class="card-body bg-light overflow-auto" id="messages-list">
        {% for message in room.messages.all %}
        <div class="d-flex flex-column m-2 border rounded bg-white">
            <div class="p-2 text-muted"><strong>{{message.sender}}</strong></div>
            <div class="p-2">{{message.content}}</div>
        </div>
        {% endfor %}
    </div>
    <div class="card-footer">
        <form method="post" id="form-message">
            <div class="input-group mb-3">

                <input type="text" class="form-control" placeholder="Write your message Here" id="room-message-input"
                    required>
                <button class="btn btn-primary" type="button" id="room-message-submit">
                    <i class="bi bi-send"></i>
                </button>

            </div>
        </form>
    </div>
</div>
{% endblock container %}


{% block scripts %}
{{ room.pk|json_script:"room-id" }}
{{ request.user.email |json_script:"user-email" }}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
<script>

    const roomId = JSON.parse(document.getElementById('room-id').textContent)
    const userEmail = JSON.parse(document.getElementById('user-email').textContent)
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/rooms/'
        + roomId
        + '/'
    );

    chatSocket.onclose = function (e) {
        console.log('onclose')
    }

    chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        if (data.message) {
            const newMessage = '<div class="d-flex flex-column m-2 border rounded bg-white">'
                + '<div class="p-2 text-muted"><strong>' + data.useremail + '</strong></div>'
                + '<div class="p-2">' + data.message + '</div>'
                + '</div>'
            document.querySelector('#messages-list').innerHTML += (newMessage);
        } else {
            alert('The message was empty!');
        }

    };

    $('#form-message').submit(function (e) {
        e.preventDefault(); // Prevent the default form submission
        const messageInput = $('#room-message-input');
        const message = messageInput.val();
        chatSocket.send(JSON.stringify({
            'message': message,
            'useremail': userEmail,
            'room_id': roomId
        }));
        messageInput.val('');
    });
</script>
{% endblock scripts %}

templates/rooms/list.html
{% extends 'base.html' %}


{% block head_content %}
<title>My Rooms</title>
{% endblock head_content %}


{% block container %}

{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}


{% if rooms.count > 0 %}

<div class="container text-center">
    <div>
        <h1>Rooms</h1>
    </div>
    <hr>
    <div class="row row-cols-5 g-4">
        {% for room in rooms %}
        <div class="col">
            <div class="card bg-light">
                <div class="card-body">
                    <h5 class="card-title">{{room.name}}</h5>
                    <a class="btn btn-primary w-100 stretched-link" href="{% url 'rooms:detail' room.pk %}">JOIN</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% else %}
<div class="countainer border rounded">
    No rooms created
</div>
{% endif %}


{% endblock container %}