apps/rooms/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'rooms', views.RoomViewSet, basename='api-rooms')
router.register(r'messages', views.MessageViewSet, basename='api-messages')

urlpatterns = [
    path('', views.RoomsListView.as_view(), name='list'),
    path('create/', views.RoomCreateView.as_view(), name='create'),
    path('rooms/<int:pk>/', views.RoomDetailView.as_view(), name='detail'),
    path('api/', include(router.urls)),
]

apps/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('api/<int:pk>/', views.UserAPIView.as_view(), name='api-detail'),
]

room_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.rooms.urls', 'rooms'), namespace='rooms')),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path(
        'api-auth/',
        include(
            'rest_framework.urls',
            namespace='rest_framework',
        ),
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    {% block scripts %}{% endblock scripts %}

</body>

</html>

templates/navbar.html
<nav class=" navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">

        <a class="navbar-brand text-white" href="{% url 'rooms:list' %}">ROOMS</a>

        <form class="d-flex flex-grow-1 me-2" role="search" action="{% url 'rooms:list' %}">
            <div class="input-group">
                <input class="form-control" name="q" value="{{q}}" type="search" placeholder="Search for room"
                    aria-label="Search" required>
            </div>
        </form>

        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'rooms:create' %}"><i class="bi bi-plus-lg"></i></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    {{request.user.email}}
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                </ul>
            </li>

            {% else %}
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'users:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>