apps/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('api/<int:pk>/', views.UserAPIView.as_view(), name='api-detail'),
]

room_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.rooms.urls', 'rooms'), namespace='rooms')),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),
    path(
        'api-auth/',
        include(
            'rest_framework.urls',
            namespace='rest_framework',
        ),
    ),
]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = False
    email = models.EmailField(unique=True)
    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email

apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import User


class EmailAuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(),
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('Invalid email or password.')
        return cleaned_data


class EmailRegistrationForm(forms.Form):
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
    )
    first_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        min_length=5,
        max_length=70,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password_confirmation = forms.CharField(
        min_length=5,
        max_length=70,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("User with this email already exists")
        return email

    def clean(self):
        data = super().clean()
        if data['password'] != data['password_confirmation']:
            raise forms.ValidationError("Passwords don't match")
        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')
        return User.objects.create_user(**data)

apps/users/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import FormView
from django.contrib.auth import authenticate, login
from django.conf import settings
import logging
from rest_framework.generics import RetrieveAPIView

from .models import User
from .forms import EmailAuthenticationForm, EmailRegistrationForm
from .serializers import UserSerializer
from .permissions import isSelf

logger = logging.getLogger('main')


# Create your views here.
class LoginView(SuccessMessageMixin, FormView):
    template_name = 'users/login.html'
    form_class = EmailAuthenticationForm
    success_url = settings.LOGIN_REDIRECT_URL
    success_message = "Welcome Back!"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password'],
        )
        login(self.request, user)
        logger.info(f'user {user} authenticated succesfully')
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """LogoutView"""


class SignUpView(SuccessMessageMixin, FormView):
    template_name = 'users/signup.html'
    form_class = EmailRegistrationForm
    success_url = settings.LOGIN_REDIRECT_URL
    success_message = (
        'Welcome to our chat app! '
        'Feel free to create new rooms and chat with everyone'
    )

    def form_valid(self, form):
        user = form.save()
        logger.info(f'signup of user {user} into the app')
        login(self.request, user)
        logger.info(f'logging user {user} into the app')
        return super().form_valid(form)


# API VIEWS
class UserAPIView(RetrieveAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    permission_classes = [
        isSelf,
    ]

templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>

<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

</body>

</html>

templates/users/login.html
{% extends 'users/base.html' %}

{% block title %}
<title>Sign In</title>
{% endblock %}

{% block container %}
<div class="container mt-5 w-75 border rounded text-center">
    <h1>Sign In</h1>

    {% if form.errors %}
    <p class="alert alert-danger"> Invalid Username or Password. Please Try Again</p>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">{% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="email" placeholder="Email" name="email">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password">
        </div>
        <br>
        <button class="btn btn-primary w-100" type="submit">Sign in</button>
    </form>
    <p class="mt-4">Don't have an account yet? <a href="{% url 'users:signup' %}">Sign Up Here</a></p>
</div>
{% endblock %}

templates/users/signup.html
{% extends 'users/base.html' %}

{% block head_content %}
<title>Sign Up</title>
{% endblock head_content %}


{% block container %}
<div class="container border rounded">
    <h1 style="text-align: center;">Sign Up</h1>

    {% if error %}
    <p class="alert alert-danger">{{error}}</p>
    {% endif %}

    <form action="{% url 'users:signup' %}" method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary w-100 btn-block mb-3" type="submit">Register</button>
    </form>
</div>
{% endblock container %}